# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a44f89ede17775a212a042e7fb9a863fbd5fd937d4b172374a10e94097a93c795a434a736c2464e8a6ea499de563f519e66103160f16e09e2ae78593e1a7fecc

test:
  secret_key_base: 0c971af50b8a2ab18bf59c63eda53f6d43fd1a30b55de53f8d417e16f98b4c9d81c9f349ad850f75df712ce17f92464df10b59d13cf0bac6cd0d840481c27209

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
